### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by OlivierJM** [OlivierJM/intro-react#1]
This is a plain react app.  

Our task will be simple we need to create a weather app, we will an API for this. 

Get data from the API and display properly in the app and have it automatically update when it changes.

**Comment by aaronjeke** [comment]
So am having a challenge with creating a Component, I don't understand what needs to imported depending on the component being created and also the render part, what am I to render? Also I tried saving my work after editing and it distorted whatever code I had written, what could be wrong?

**Comment by OlivierJM** [comment]
@aaronjeke when creating a component there are few things you need to know.

There are currently 2 types of components

- class based components(stateful)
- functional components(stateless)

when creating a component, you need to import React and that is basically what you need

**Comment by OlivierJM** [comment]
```Javascript 

import React, { Component } from 'react'; // here you are importing React, and component since the class extends it
import logo from './logo.svg'; // this is just an SVG logo
import './App.css'; // you can also import css if you have it

// when creating a class based component, you need to extend the component imported from react,
class App extends Component { 
// all other methods for this class based component can go here

  render() { // render is simply a method of this class that returns the defined UI in the return
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App; // you can export it, so that you use it in other components

```

**Comment by aaronjeke** [comment]
So when I tried to test my code, I got this error below;

Parsing error: Unexpected token, expected ";"

I have gone through the code several times and I see nothing wrong with the formatting. Help?

**Comment by OlivierJM** [comment]
I can only help when I see the code

**Comment by OlivierJM** [comment]
I have added comments to specify what's wrong with the file

**Comment by OlivierJM** [comment]
@aaronjeke  If you have understood this, I am closing this issue.

**Comment by aaronjeke** [comment]
Yes we can close this. I understand the difference between a class based
and function based component and how they can be used.

**Comment by OlivierJM** [comment]
Thanks, I am glad it helped.
